config/routes.rb
JamesPortfolio::Application.routes.draw do

  devise_for :admins

  get 'tags/:tag', to: 'static_pages#show', as: :tag

  resources :articles
  resources :contacts

  match 'work' => 'static_pages#work'
  match 'social' => 'contact#new'

  root :to => 'static_pages#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable

  attr_accessible :email, :password, :password_confirmation
end

app/models/article.rb
class Article < ActiveRecord::Base
  attr_accessible :name, :content, :tag_list, :created_at
  acts_as_taggable
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  attr_accessible :message, :name, :email, :subject, :message_id, :created_at
end

app/models/static_page.rb
class StaticPage < ActiveRecord::Base
  attr_accessible :tag_list
  acts_as_taggable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :authenticate_admin!, except: [:index, :show]

  def index
    @articles = Article.all
  end

  def show
    @article = Article.find(params[:id])
  end

  def new
    @article = Article.new
  end

  def edit
    @article = Article.find(params[:id])
  end

  def create
    @article = Article.new(params[:article])
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Post was successfully created.' }
      else
        format.html { render action: 'new' }
      end
    end
  end

  def update
    @article = Article.find(params[:id])

    respond_to do |format|
      if @article.update_attributes(params[:article])
        format.html { redirect_to @article, :notice => 'Post was successfully updated.' }
      else
        format.html { render action: 'edit' }
      end
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy

    respond_to do |format|
      format.html { redirect_to articles_url }
    end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(params[:contact])
    respond_to do |format|
      if @contact.save
        format.html { redirect_to social_path, notice: 'Message sent successfully!' }
      else
        format.html { render action: 'new' }
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def index
    @articles = Article.all
    @article = Article.offset(rand(Article.count)).first
  end

  def show
    if params[:tag]
      @articles = Article.tagged_with(params[:tag])
    else
      @articles = Article.all
    end
  end

  def social

  end

  def work

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML,
        :autolink => true, :space_after_headers => true)
    markdown.render(text).html_safe
  end
  # <div class="alert-box [success alert secondary]">
  #   This is an alert box.
  #   <a href="" class="close">&times;</a>
  # </div>
  DEFAULT_KEY_MATCHING = {
    :alert     => :alert,
    :notice    => :success,
    :info      => :standard,
    :secondary => :secondary,
  }
  def display_flash_messages(key_matching = {})
    key_matching = DEFAULT_KEY_MATCHING.merge(key_matching)

    flash.inject "" do |message, (key, value)|
      message += content_tag :div, :data => { :alert => "" }, :class => "alert-box #{key_matching[key] || :standard}" do
        (value + link_to("&times;".html_safe, "#", :class => :close)).html_safe
      end
    end.html_safe
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :tag_list, "Tags (separated by commas)" %>
    <%= f.text_field :tag_list %>
    <%= f.label :content %>
    <%= f.text_area :content, :class => "postInput"%>
  </div>
  <div class="actions">
    <%= f.submit :class => "button" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>My mindless ramblings*</h1>

<% @articles.each do |article| %>

  <div class="panel">

    <h3><%= link_to article.name, article_path(article) %></h3>
    <p class="subheader">
      <%= truncate(article.content, :length => 250) %>
      </br>
    </p>
    <%  %>
    <%= link_to 'Read more...', article_path(article) %>
    <% if admin_signed_in? %>
      <ul class="button-group radius">
        <li><%= link_to 'Show', article, class: "button" %></li>
        <li><%= link_to 'Edit', edit_article_path(article), class: "button secondary" %></li>
        <li><%= link_to 'Delete', article, method: :delete,
                                            data: { confirm: 'Are you sure?' },
                                            class: "button alert" %>
        </li>
        <li><%= link_to 'New Article', new_article_path,
                             class: "button success radius" %>
        </li>
      </ul>
    <% end %>
  </div>

<% end %>

<small>*Please do not judge the content of my character based upon my writing or writing style. I write in order to get better at writing. Hopefully my writing will improve over time, and this is my way of keeping a record of that progress. Thank you for your understanding.</small>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<%= link_to 'Back to article listing', articles_path, class: "right" %>
<h3><%= @article.name %></h3>
<p class="subheader">
  <%= markdown(@article.content) %>
</p>
<%= link_to 'Back to article listing', articles_path, class: "right" %>

<% if admin_signed_in? %>
  <%= link_to 'Edit', edit_article_path(@article), class: "button" %>

<% end %>

app/views/contact/_form.html.erb
<%= form_for @contact do |f| %>
  <% if @contact.errors.any? %>
    <h2>
      <%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:
    </h2>

    <ul>
    <% @contact.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  <% end %>
<div class="row collapse">
  <div class="large-2 columns">
    <%= f.label :name, :class => 'inline' %>
  </div>
  <div class="large-10 columns">
    <%= f.text_field :name, :placeholder => 'Kenny Powers' %>
  </div>
</div>
<div class="row collapse">
  <div class="large-2 columns">
    <%= f.label :subject %>
  </div>
  <div class="large-10 columns">
    <%= f.text_field :subject %>
  </div>
</div>
<div class="row collapse">
  <div class="large-2 columns">
    <%= f.label :email %>
  </div>
  <div class="large-10 columns">
    <%= f.text_field :email, :placeholder => 'kennypowers@example.com' %>
  </div>
</div>
<div class="row collapse">
  <div class="large-2 columns">
    <%= f.label :message %>
  </div>
  <div class="large-10 columns">
    <%= f.text_area :message %>
  </div>
</div>
<div class="row collapse">
  <div class="large-2 columns end">
    <%= f.submit %>
  </div>
</div>
<% end %>

app/views/contact/new.html.erb
<div class="panel secondary">You're likely to find me up late hacking on projects, or up early learning. Don't hesitate to get in contact if you'd like to collaborate on a project, or you're looking for a co-founder!</div>
<div class="row">
  <div class="large-4 columns">
    <a href="http://www.github.com/JamesDullaghan">
      <i class="social foundicon-github large"></i><br>
      <span class="subheader">Github:</span> JamesDullaghan
    </a>
  </div>
  <div class="large-4 columns">
    <a href="http://www.twitter.com/JamesDullaghan">
      <i class="social foundicon-twitter large"></i><br>
      <span class="subheader">Twitter:</span> @JamesDullaghan
    </a>
  </div>
  <div class="large-4 columns end">
    <a href="mailto:james@fldlvl.com?Subject=Hi%there">
      <i class="general foundicon-mail large"></i><br>
      <span class="subheader">Email:</span> James[@]fldlvl.com
    </a>
  </div>
</div>
<br>

<div class="row">

  <!-- Contact Details -->
  <div class="large-9 columns">

    <h3>Get in Touch!</h3>
    <p>I'd love to hear from you. You can reach out to me and I will get back to you. I love getting email <em>all day</em>.</p>

    <div class="section-container tabs" data-section>
      <section class="section">
        <h5 class="title"><a href="#panel1">Contact Me</a></h5>
        <div class="content" data-slug="panel1">
          <%= render 'form' %>
        </div>
      </section>
    </div>
  </div>

  <!-- End Contact Details -->
</div>

app/views/layouts/_footer.html.erb
<footer>
  <hr />
  <div class="row">
    <div class="large-4 columns">
      <p><a href="/">&copy;</a><%= link_to ' Copyright Pando LLC.', root_path %></p>
    </div>
    <div class="large-8 columns">
      <ul class="inline-list right">
        <li><%= link_to 'Home', root_path %></li>
        <li><%= link_to 'Mindless rambling', articles_path %></li>
        <li><%= link_to 'Some of my work', work_path %></li>
        <li><%= link_to 'Where to find me', social_path %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<div class="sticky">
  <nav class="top-bar">
    <%#= image_tag('Pando_web_logo.png',
                                      :alt => "Pando Web Logo",
                                      :width => "40", :height => "40",
                                      :class => "logo-image right") %>
    <ul class="title-area">
      <!-- Title Area -->
      <li class="name">
        <h1>
          <% @name = '<span class="abbr">J</span><span class="hide-on-hover">ames&nbsp;</span><span class="abbr">D</span><span class="hide-on-hover">ullaghan</span>' %>
          <%= @name.html_safe %>
        </h1>
      </li>
      <li class="divider"></li>
      <!-- Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone -->
      <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
    </ul>

    <section class="top-bar-section">
      <!-- Right Nav Section -->
      <ul class="right">
        <li class="divider"></li>
        <li><%= link_to 'Home', root_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Words', articles_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Work', work_path %></li>
        <li class="divider"></li>
        <li><%= link_to 'Contact', social_path %></li>
        <li class="divider"></li>
        <li class="empty-button"></li>
      </ul>
    </section>
  </nav>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
  <head>
  	<meta charset="utf-8" />

  	<!-- Uncomment to make IE8 render like IE7 -->
  	<!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  	<!-- Set the viewport width to device width for mobile -->
  	<meta name="viewport" content="width=device-width, initial-scale=1.0" />

  	<title><%= content_for?(:title) ? yield(:title) : "James Dullaghan" %></title>

  	<%= stylesheet_link_tag    "application" %>
  	<%= javascript_include_tag "vendor/custom.modernizr" %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <%= render 'layouts/header' %>
    <%= display_flash_messages %>
    <div class="row container">

      <%= yield %>

    </div>

    <%= render 'layouts/footer' %>

    <%= javascript_include_tag "application" %>
  </body>
</html>

app/views/static_pages/_categories.html.erb
<h5>Categories</h5>
<ul class="side-nav">
  <li>
    <%= link_to 'News', tag_path('News') %>
  </li>
  <li>
    <%= link_to 'Code', tag_path('Code') %>
  </li>
  <li>
    <%= link_to 'Design', tag_path('Design') %>
  </li>
  <li>
    <%= link_to 'Startups', tag_path('Startups') %>
  </li>
</ul>

app/views/static_pages/_featured.html.erb
<div class="panel">
  <h5>Featured Article</h5>
  <h6 class="subheader">
    <%= link_to @article.name, article_path(@article) %>
  </h6>
  <p><%= truncate(@article.content, :length => 150) %></p>
</div>

<div class="panel">
  <h5>Sponsor</h5>
  <a href="http://www.pandodev.com">
    <%= image_tag 'Pando_Tree_v1.png', alt: 'Pando development logo', width: 235, height: 235 %>
    <h6 class="subheader text-center">PANDO WEB DEVELOPMENT
  </a>
  </h6>
</div>

app/views/static_pages/index.html.erb
<!-- Main Content -->

  <%= render template: 'static_pages/show' %>

  <!-- Sidebar -->

  <aside class="large-4 columns">

    <%= render 'categories' %>

    <%= render 'featured' %>

  </aside>

  <!-- End Sidebar -->

<!-- End Main Content -->

app/views/static_pages/show.html.erb
<section class="large-8 columns" role="content">
<% @articles.each do |article| %>
  <article>
    <!-- Article Title -->

    <h3><%= link_to article.name, article_path(article) %></h3>

    <!-- Authored Date -->

    <h6>Written on <%= article.created_at.strftime("%B %d, %Y") %></h6>

    <!-- Article Preview -->

    <p class="articlePreview">
      <%= truncate(article.content, :length => 275) %>
    </p>
    <ul class="inline-list">
      <li>Tags:</li><br>
      <% article.tag_list.each do |t| %>
      <li>
        <span class="secondary label">
          <%= link_to t, tag_path(t).html_safe %>
        </span>
      </li>
      <% end %>
    </ul>

    <!--ul class="inline-list">
      <li>Tags:
        <span class="secondary label">
          <%= article.tag_list.map { |t| link_to t, tag_path(t) }.join(', ').html_safe %>
        </span>
      </li>
    </ul-->
    </br>
    <%= link_to 'Read more...', article_path(article) %>
  </article>
  <hr>
<% end %>
</section>

app/views/static_pages/social.html.erb
<!-- 

I copied the text from HERE and put it in the dynamic /contact/new.html.erb

I also added 'resource :contacts' in your routes (so that RESTful architecture works for contact-resource as well)

You can delete this social.html.erb site now ;)

-->

app/views/static_pages/work.html.erb
<div class="row">
  <div class="large-11 large-offset-1 columns">
    <ul class="clearing-thumbs" data-clearing>
      <li>
        <a href="/assets/portfolio/portfolio_1.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_1_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_2.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_2_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_3.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_3_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_3_1.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_3_1_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_4.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_4_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_5.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_5_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_5_1.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_5_1_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_6.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_6_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_6_1.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_6_1_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_7.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_7_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_8.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_8_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_9.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_9_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_9_1.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_9_1_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_10.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_10_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_11.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_11_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_11_1.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_11_1_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_16.png" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_16_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_13.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_13_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_14.jpg" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_14_TH.jpg' %>
        </a>
      </li>
      <li>
        <a href="/assets/portfolio/portfolio_15.png" class="th radius">
          <%= image_tag 'portfolio/thumbnails/portfolio_15_TH.jpg' %>
        </a>
      </li>
    </ul>
  </div>
</div>